spring.application.name=Hospital Management System

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-dae5jp7qj5pc73abpv8g-a.singapore-postgres.render.com/hospital_db_0zxr?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:hospital_db_0zxr_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:VaAD3vkxcHofVuZ8lbJOGIm4EhxZH4Bo}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

server.port=${PORT:8080}

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=20000