spring.application.name=Hospital Management System

# PostgreSQL Database Connection (Render + Local)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-dae5jp7qj5pc73abpv8g-a.singapore-postgres.render.com/hospital_db_0zxr?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:hospital_db_0zxr_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:VaAD3vkxcHofVuZ8lbJOGIm4EhxZH4Bo}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Template Engine Settings
spring.thymeleaf.cache=false

# Port Configuration (Render auto-injects PORT variable)
server.port=${PORT:8080}